name: Upload recent log files

on: [push, workflow_dispatch]

jobs:
  upload:
    runs-on: ubuntu-22.04
    steps:
      - name: find-r
        run: |
          log_files=$(find /home/runner/runners/ -type f -name "*.log" -mmin -3)
          echo "::set-output name=log_files::$log_files"
        id: find_logs  

      - name: Upload modified log files
        uses: actions/upload-artifact@v3
        with:
          name: modified-logs
          path: |
            {% for file_path in steps.find_logs.outputs.log_files.split('\n') %}
              {{ file path }}
            {% endfor %}
