name: Upload modified logs

on: [push, workflow_dispatch]

jobs:
  upload_logs:
    runs-on: ubuntu-22.04
    steps:
      - name: List
        run: |
          sudo find / -name '*.log' -mmin -1
      - uses: actions/checkout@v3
      - name: Get modified logs
        run: |
          git diff --name-only HEAD^ HEAD | grep '.log$' > modified_logs.txt
          echo "::set-output name=modified_logs::$(cat modified_logs.txt)"
        id: get_modified_logs
      - name: Upload modified log files
        uses: actions/upload-artifact@v3
        with:
          name: modified-logs
          path: |
            ${{ join(fromJson(steps.get_modified_logs.output.modified_logs), '\n') }}
