name: Run tests for my project

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Print
        run: |
          pwd
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
      - name: List
        run: |
          sudo find / -name '*.log' -mmin -3
      - name: Upload modified log files
        uses: actions/upload-artifact@v3
        with:
          name: modified-logs
          path: |
            /home/runner/runners/2.301.1/_diag/pages/5bc5fd15-c8b2-46a3-9dc2-f966d9874587_11aca8ad-0a37-5dd8-39d0-af4dbbe8cc80_1.log
            /home/runner/runners/2.301.1/_diag/pages/5bc5fd15-c8b2-46a3-9dc2-f966d9874587_312e9aa0-de28-546d-3462-8d46f0cf99e7_1.log
            /var/log/cloud-init-output.log
            /run/cloud-init/cloud-init-generator.log
